model_name_or_path: /data0/models/Qwen2.5-7B-Instruct
trust_remote_code: true
stage: sft
do_train: true
finetuning_type: full
deepspeed: /data0/users/yuanh/LLaMA-Factory/examples/deepspeed/ds_z3_offload_config.json
dataset: math_first_longskip_60
template: qwen
cutoff_len: 4096
max_samples: null
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4
output_dir: /data1/users/yuanh/saves/qwen2.5-7B-Instruct/sft_full/math220k_first_longskip_60_4096
logging_steps: 2
save_steps: 3000
plot_loss: true
overwrite_output_dir: true
save_only_model: false
per_device_train_batch_size: 2
gradient_accumulation_steps: 1
learning_rate: 1.0e-05
num_train_epochs: 3
lr_scheduler_type: cosine
warmup_ratio: 0.05
bf16: true
resume_from_checkpoint: null
optim: adamw_torch
adam_beta1: 0.9
adam_beta2: 0.95
weight_decay: 0.0001
use_swanlab: true
swanlab_run_name: 14B_full_math220k_first_longskip_60_4096
swanlab_api_key: 
